const apiUrl = "http://localhost:300"; // Salvar a url do backend em uma variavel para ser utilizada depois na hora chamada da api...

const catalogo = document.getElementById("catalogo");// Mapea o elemento "CATALOGO" (<table></table>) do html...