


/**
 *  5°) API - Forma de comunicação entre sistemas que contem endereços (End Points)...
 *  API REST - Permite o uso GET/POST/PUT/DELETE...
 *  Criar um endpoit para retomar um msg para o cliente...
 *
 */
 app.get("/", (req, res) => {
    /**
     * REQ - (RESQUEST/REQUISIÇÃO) --- Vem do Usuário...
     * RES - (RESPONSE/RESPOSTA) ----- Volta para o Usuário...
     */
    res.send("Olá, tudo ok!");
  });
  
  // 8°) [GET] /lista - retorna a lista de albuns...
  app.get("/albuns", (req, res) => {
    res.send(lorenzoAlbuns);
  });
  
  // 9°) [Get] /lista/{id} - retornando ao usuário um único album de acordo com o id...
  app.get("/albuns/:id", (req, res) => {
    const idParam = req.params.id; // Acessa o id via a requisicao...
    const albumEncontrado = lorenzoAlbuns.find((album) => album.id == idParam); // Busca um item de acordo com seu id, Procurando na lista um album que contenha o id igula ao que foi recebido via parametro...
    res.send(albumEncontrado); // envia para o Front-End o album encontrado...
  });